#!/usr/bin/env python3
"""Build london-outline.svg from the London boroughs TopoJSON.

Source: londonBoroughs.json from https://github.com/vega/vega-datasets
(simplified from the London Datastore "London_Borough_Excluding_MHW"
boundaries, OGL-UK-3.0). Because the boundaries exclude the river below mean
high water, the Thames appears as a channel between the boroughs.

Usage: python tools/build_london_outline.py path/to/londonBoroughs.json

The projection constants printed at the end must match PROJECTION in
station-map.js; tests/station-map.test.mjs checks that they do.
"""

from __future__ import annotations

import json
import math
import sys
from collections import Counter
from pathlib import Path

WIDTH = 1000
PAD = 20
OUTPUT = Path(__file__).resolve().parent.parent / "london-outline.svg"


def decode_arcs(topology: dict) -> list[list[tuple[float, float]]]:
    scale_x, scale_y = topology["transform"]["scale"]
    shift_x, shift_y = topology["transform"]["translate"]
    arcs = []
    for arc in topology["arcs"]:
        x = y = 0
        points = []
        for dx, dy in arc:
            x += dx
            y += dy
            points.append((x * scale_x + shift_x, y * scale_y + shift_y))
        arcs.append(points)
    return arcs


def polygon_rings(geometry: dict) -> list[list[int]]:
    if geometry["type"] == "Polygon":
        return geometry["arcs"]
    if geometry["type"] == "MultiPolygon":
        return [ring for polygon in geometry["arcs"] for ring in polygon]
    return []


def main(source: Path) -> None:
    topology = json.loads(source.read_text(encoding="utf-8"))
    arcs = decode_arcs(topology)
    geometries = next(iter(topology["objects"].values()))["geometries"]

    lon_min, lat_min, lon_max, lat_max = topology["bbox"]
    cos_lat = math.cos(math.radians((lat_min + lat_max) / 2))
    scale = (WIDTH - 2 * PAD) / ((lon_max - lon_min) * cos_lat)
    height = round((lat_max - lat_min) * scale + 2 * PAD)

    def project(lon: float, lat: float) -> tuple[float, float]:
        return (PAD + (lon - lon_min) * cos_lat * scale, PAD + (lat_max - lat) * scale)

    def oriented(index: int) -> list[tuple[float, float]]:
        return arcs[index] if index >= 0 else arcs[~index][::-1]

    usage = Counter()
    for geometry in geometries:
        for ring in polygon_rings(geometry):
            for index in ring:
                usage[index if index >= 0 else ~index] += 1

    def line_path(indices: list[int]) -> str:
        parts = []
        for index in indices:
            points = [project(*point) for point in arcs[index]]
            parts.append("M" + "L".join(f"{x:.1f} {y:.1f}" for x, y in points))
        return "".join(parts)

    # Arcs used by one borough are the Greater London boundary and the Thames
    # banks; arcs shared by two boroughs are internal borough boundaries.
    edge_arcs = sorted(index for index, count in usage.items() if count == 1)
    internal_arcs = sorted(index for index, count in usage.items() if count > 1)

    land = []
    for geometry in geometries:
        for ring in polygon_rings(geometry):
            points = []
            for position, index in enumerate(ring):
                segment = oriented(index)
                points.extend(segment if position == 0 else segment[1:])
            projected = [project(*point) for point in points]
            land.append("M" + "L".join(f"{x:.1f} {y:.1f}" for x, y in projected) + "Z")

    svg = f"""<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {WIDTH} {height}" data-projection="lonMin={lon_min:.6f} latMax={lat_max:.6f} cosLat={cos_lat:.6f} scale={scale:.4f} pad={PAD}">
<!-- Greater London boroughs and the River Thames. Generated by tools/build_london_outline.py. -->
<!-- Contains National Statistics data (c) Crown copyright and database right 2015. Contains Ordnance Survey data (c) Crown copyright and database right 2015. Open Government Licence v3.0. -->
<path d="{''.join(land)}" fill="#f3f3f0" stroke="none"/>
<path d="{line_path(internal_arcs)}" fill="none" stroke="#c9c9c4" stroke-width="0.75" stroke-linejoin="round" vector-effect="non-scaling-stroke"/>
<path d="{line_path(edge_arcs)}" fill="none" stroke="#111111" stroke-width="1.1" stroke-linejoin="round" stroke-linecap="round" vector-effect="non-scaling-stroke"/>
</svg>
"""
    OUTPUT.write_text(svg, encoding="utf-8")
    print(f"Wrote {OUTPUT} ({len(svg.encode()):,} bytes, viewBox 0 0 {WIDTH} {height})")
    print(f"PROJECTION = {{ lonMin: {lon_min:.6f}, latMax: {lat_max:.6f}, cosLat: {cos_lat:.6f}, scale: {scale:.4f}, pad: {PAD}, width: {WIDTH}, height: {height} }}")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    main(Path(sys.argv[1]))
